name: Generate Docs
on: [push]
jobs:
  Generate-C4-Diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate C1
        uses: university-of-york/generate-c4-model-action@1.0.0
        with:
          source-path: docs/c4/c1.dsl
          target-path: docs/c4
      - name: Generate C2
        uses: university-of-york/generate-c4-model-action@1.0.0
        with:
          source-path: docs/c4/c2.dsl
          target-path: docs/c4
      - name: Generate C3
        uses: university-of-york/generate-c4-model-action@1.0.0
        with:
          source-path: docs/c4/c3.dsl
          target-path: docs/c4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/c4/*.png
          git commit -m "C4 diagrams generated."
          git push